version: '3.4'

services:
  dotnetmovieportal:
    image: ${DOCKER_REGISTRY-}dotnetmovieportal
    build:
      context: .
      dockerfile: dotnetmovieportal/Dockerfile
      

  sqlserverService:  
    image: harbor.init.de/microsoft/mssql/server:2019-CU13-ubuntu-16.04  
    hostname: 'sqlserver'  
    environment:  
      ACCEPT_EULA: Y  
      SA_PASSWORD: "BigPassw0rd"  
    volumes:  
      - ./data/mssql:/var/opt/mssql3  
    ports:  
      - '1433:1433'  
    expose:  
      - 1433  